CREATE TABLE IF NOT EXISTS Estudantes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    MATRICULA INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Livros (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    TITULO TEXT NOT NULL,
    AUTOR TEXT NOT NULL
);